# Linear Algebra

## Matrices & vectors

+ Dimension of matrices: numb_rows x numb_columns

In [4]:
import numpy as np 

m1 = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
print("m1 = \n {} \n".format(m1))
print("m1's shape: {}".format(m1.shape))

m1 = 
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

m1's shape: (3, 3)


In [9]:
def multi_matrices(a: np.array, b: np.array) -> np.array:
    assert(a.shape[1] == b.shape[0])
    c = np.dot(a, b)
    print("The result matrix: \n {}".format(c))

a = np.array([[1, 2, 3], [3, 4, 5]])
b = np.array([[1, 2], [2, 3], [4, 5]])
multi_matrices(a, b)

The result matrix: 
 [[17 23]
 [31 43]]


## Determinant, rank, inverse & transpose

+ Determinant of square matrix A denotes det(A) or |A|

+ In python, **np.linalg.det(A)**


In [10]:
# def determinant_matrix(a: np.array) -> int:
#     assert(a.shape[0] == a.shape[1])


### Inverse matric

+ Identity matrix: a[i, i] = 1 & other elements = 0

+ Inverse A(-1): A.A(-1)=I

In [13]:
m1 = np.array([[0, 1], [3, 0]])
print("Inverse matrix: \n {}".format(np.linalg.inv(m1)))

Inverse matrix: 
 [[0.         0.33333333]
 [1.         0.        ]]


### Transpose

+ A(n, m) -> Transpose B (m, n):
    - Aij = Bji