## Tham khao:

+ https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/keras/backend.py#L4426

+ https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/ops/nn_ops.py#L3304


In [1]:
import tensorflow as tf
from tensorflow.keras import backend as K



## Categorical crossentropy

In [2]:
a = tf.constant([1., 0., 0., 0., 1., 0., 0., 0., 1.], shape=[3,3])
print("a: ", a)
b = tf.constant([.9, .05, .05, .5, .89, .6, .05, .01, .94], shape=[3,3])
print("b: ", b)

loss_ab = K.categorical_crossentropy(a, b)
print("Categorical cross entropy between a & b: {}".format(loss_ab))
loss_aa = K.categorical_crossentropy(a, a)
print("Categorical cross entropy between a & a: {}".format(loss_aa))


a:  tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
b:  tf.Tensor(
[[0.9  0.05 0.05]
 [0.5  0.89 0.6 ]
 [0.05 0.01 0.94]], shape=(3, 3), dtype=float32)
Categorical cross entropy between a & b: [0.10536055 0.8046684  0.06187541]
Categorical cross entropy between a & a: [1.1920929e-07 1.1920929e-07 1.1920929e-07]


## Sparse cross entropy 

In [ ]:
a = tf.constant([1., 0., 0., 0., 1., 0., 0., 0., 1.], shape=[3,3])
print("a: ", a)
b = tf.constant([.9, .05, .05, .5, .89, .6, .05, .01, .94], shape=[3,3])
print("b: ", b)

loss_ab = K.categorical_crossentropy(a, b)
print("Categorical cross entropy between a & b: {}".format(loss_ab))
loss_aa = K.categorical_crossentropy(a, a)
print("Categorical cross entropy between a & a: {}".format(loss_aa))